# pyscn configuration file
# This is a dedicated TOML configuration file (like ruff.toml)
# Note: No [tool.pyscn] prefix needed in .pyscn.toml files

# Analysis settings
[analysis]
min_lines = 5
min_nodes = 10
max_edit_distance = 50.0
ignore_literals = false
ignore_identifiers = false
cost_model_type = "python"

# Threshold settings for clone type classification
[thresholds]
type1_threshold = 0.98
type2_threshold = 0.95
type3_threshold = 0.85
type4_threshold = 0.70
similarity_threshold = 0.8

# Input settings
[input]
paths = ["."]
recursive = true
include_patterns = ["*.py"]
exclude_patterns = ["test_*.py", "*_test.py", "__pycache__/*"]

# Output settings
[output]
format = "text"
show_details = false
show_content = false
sort_by = "similarity"
group_clones = true

# Filtering settings
[filtering]
min_similarity = 0.0
max_similarity = 1.0
enabled_clone_types = ["type1", "type2", "type3", "type4"]
max_results = 10000

# Grouping settings
[grouping]
mode = "connected"
threshold = 0.85
k_core_k = 2

# LSH acceleration settings
[lsh]
enabled = "auto"
auto_threshold = 500
similarity_threshold = 0.78
bands = 32
rows = 4
hashes = 128

# Performance settings
[performance]
max_memory_mb = 100
batch_size = 100
enable_batching = true
max_goroutines = 4
timeout_seconds = 300